version: '3.7'

services:
  chilkatftp:
    image: ${DOCKER_REGISTRY-}chilkatftp
    container_name: filebridge-ftpclient-chilkat
    build:
      context: .
      dockerfile: ChilkatFtp/Dockerfile
    volumes:
      - "/d/ftp/upload:/var/ftp/upload"
      - "/d/ftp/download:/var/ftp/download"
    environment:
      - CPFileBridge_SftpOptions__Host=filebridge-sftp
      - CPFileBridge_SftpOptions__LocalUploadFolder=/var/ftp/upload
      - CPFileBridge_SftpOptions__LocalDownloadFolder=/var/ftp/download
      - CPFileBridge_FtpsOptions__Host=filebridge-ftps
      - CPFileBridge_FtpsOptions__LocalUploadFolder=/var/ftp/upload
      - CPFileBridge_FtpsOptions__LocalDownloadFolder=/var/ftp/download
    depends_on: 
      - ftps
      - sftp
    networks:
      - cp-fb-network

  fluentrenciftp:
    image: ${DOCKER_REGISTRY-}fluentrenciftp
    container_name: filebridge-ftpclient-fluentrenci
    build:
      context: .
      dockerfile: FluentRenciFtp/Dockerfile
    volumes:
      - "/d/ftp/upload:/var/ftp/upload"
      - "/d/ftp/download:/var/ftp/download"
    environment:
      - CPFileBridge_SftpOptions__Host=filebridge-sftp
      - CPFileBridge_SftpOptions__LocalUploadFolder=/var/ftp/upload
      - CPFileBridge_SftpOptions__LocalDownloadFolder=/var/ftp/download
      - CPFileBridge_FtpsOptions__Host=filebridge-ftps
      - CPFileBridge_FtpsOptions__LocalUploadFolder=/var/ftp/upload
      - CPFileBridge_FtpsOptions__LocalDownloadFolder=/var/ftp/download
    depends_on: 
      - ftps
      - sftp
    networks:
      - cp-fb-network

 # https://hub.docker.com/r/loicmathieu/vsftpd
  ftps:
    image: loicmathieu/vsftpd
    container_name: filebridge-ftps
    command: ftps
    ports:
      - "21:21" # default ftp command port
      - "21100-21110:21100-21110" # passive mode data transfer port range
    volumes:
      - "/d/docker/ftps/share:/home/guest"
      - "/d/docker/ftps/logs:/var/log/vsftpd"
      - "/d/docker/ftps/certificate:/etc/vsftpd/private"
    networks:
      - cp-fb-network

# https://hub.docker.com/r/atmoz/sftp/
  sftp:
    image: atmoz/sftp
    container_name: filebridge-sftp
    command: foo:pass:1001
    ports:
      - "22:22" # default ssh port
    volumes:
      - "/d/docker/sftp/share:/home/foo/share"
    networks:
      - cp-fb-network

networks:
  cp-fb-network:
    name: cp-fb-network
